import '../../models/client_models.dart';

class ClientMockData {
  static const List<Product> products = [
    Product(
      id: 'P001',
      name: 'Premium Basmati Rice 5 kg',
      description: 'Long grain, aromatic basmati rice for daily use. Aged for 2 years.',
      category: 'Grains',
      price: 499.00,
      weightKg: 5.02,
      sku: 'SKU-9821-AA',
      inStock: true,
      tags: ['HEAVY'],
    ),
    Product(
      id: 'P002',
      name: 'Toor Dal 2 kg',
      description: 'Unpolished split pigeon peas, rich in protein.',
      category: 'Grains',
      price: 240.00,
      weightKg: 2.03,
      sku: 'SKU-9822-BB',
      inStock: true,
    ),
    Product(
      id: 'P003',
      name: 'Cold Pressed Coconut Oil 1 L',
      description: '100% pure cold-pressed coconut oil. Ideal for cooking and hair.',
      category: 'Oils',
      price: 350.00,
      weightKg: 0.92,
      sku: 'SKU-9823-CC',
      inStock: true,
      tags: ['LIQUID'],
    ),
    Product(
      id: 'P004',
      name: 'Organic Honey 500g Glass Jar',
      description: 'Raw, unprocessed honey sourced from deep forests.',
      category: 'Pantry',
      price: 299.00,
      weightKg: 0.85,
      sku: 'SKU-9824-DD',
      inStock: true,
      tags: ['GLASS', 'FRAGILE', 'ORGANIC'],
    ),
    Product(
      id: 'P005',
      name: 'Digestive Biscuits Family Pack',
      description: 'High-fibre wholewheat digestive biscuits.',
      category: 'Snacks',
      price: 120.00,
      weightKg: 0.54,
      sku: 'SKU-9825-EE',
      inStock: true,
      tags: ['FRAGILE', 'CRUSHABLE'],
    ),
    Product(
      id: 'P006',
      name: 'Whole Wheat Atta 10 kg',
      description: '100% MP Sharbati wheat flour.',
      category: 'Grains',
      price: 450.00,
      weightKg: 10.10,
      sku: 'SKU-9826-FF',
      inStock: true,
      tags: ['VERY HEAVY'],
    ),
    Product(
      id: 'P007',
      name: 'Turmeric Powder 200g',
      description: 'High curcumin turmeric powder.',
      category: 'Spices',
      price: 65.00,
      weightKg: 0.22,
      sku: 'SKU-9827-GG',
      inStock: true,
      tags: ['ORGANIC'],
    ),
  ];

  static const List<String> categories = ['All', 'Grains', 'Oils', 'Spices', 'Snacks', 'Pantry'];
}
